import 'package:flutter/material.dart';

class ImagesBlendPage extends StatelessWidget {
  final widthHeight = 200.0;
  @override
  Widget build(BuildContext context) {
    return Center(
        child: ListView(children: [
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.srcOver),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.srcOver),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.srcOver),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.srcOver),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.dst),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.hardLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight, height: widthHeight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.darken),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.color),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.xor),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.colorDodge),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.difference),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.srcOver),
      Image.asset('images/tears_logo.jpeg',
          width: widthHeight,
          height: widthHeight,
          color: Color.fromARGB(100, 0, 0, 200),
          colorBlendMode: BlendMode.softLight),
    ]));
  }
}
