name: flutter_talk_mar_2019
description: Sample Flutter application for my March 2019 talk.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/flutter_logo.png
    - images/flutter_logo_no_background.png
    - images/cat_tongue.gif
    - images/tears_logo.jpeg

  fonts:
    - family: Merienda
      fonts:
        - asset: assets/merienda_regular.ttf
